version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
      - "5173:5173" # For Vite dev server if needed
    environment:
      - PORT=3001
      - MONGODB_URL=mongodb://mongo:27017/scribblespace
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - ./:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: